name = "SDPSymmetryReduction"
uuid = "56ed78d6-6c87-4b01-a4f7-e143c302c7a0"
authors = ["Daniel Brosch <Daniel.Brosch@outlook.com> and contributors"]
version = "0.1.3-SD"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
